# Generated by Django 3.0.4 on 2020-03-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('content', models.TextField(verbose_name='conteudo')),
                ('date', models.DateTimeField(verbose_name='data')),
                ('priority', models.PositiveIntegerField(choices=[(0, 'Baixa'), (1, 'Média'), (2, 'Alta')], verbose_name='prioridade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='nome')),
                ('todo', models.ManyToManyField(related_name='category', to='todolist.TodoList')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
