# Generated by Django 3.0.4 on 2020-03-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='todo',
        ),
        migrations.AddField(
            model_name='todolist',
            name='category',
            field=models.ManyToManyField(related_name='todos', to='todolist.Category'),
        ),
    ]
